SystemOrganization addCategory: #'PoliteSmalltalk-LanguageBox'!
SystemOrganization addCategory: #'PoliteSmalltalk-Tests'!
SystemOrganization addCategory: #'PoliteSmalltalk-ReadabilityExtensions'!
SystemOrganization addCategory: #'PoliteSmalltalk-Applications'!
SystemOrganization addCategory: #'PoliteSmalltalk-Examples'!
SystemOrganization addCategory: #'PoliteSmalltalk-Crypto'!
SystemOrganization addCategory: #'PoliteSmalltalk-WordCount'!
